# -*- coding: utf-8 -*-
"""EmotionRec60acc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n71hUeUIpKjNaaez4C1xfY0XwAdJla6H
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
import librosa
from librosa import display
# %pylab inline
import os
import pandas as pd
import glob
import numpy as np

# Extracting features

path = '/content/drive/My Drive/Audio_Speech_Actors_01-24'
dataset_arr = []


for patht, dir, fileset in os.walk(path):
  for filename in fileset:
    X, samp_rate = librosa.load(os.path.join(patht,filename), res_type='kaiser_fast')
    #samp_rate = np.array(samp_rate)
    
    # MFCC
    mfcc_val = np.mean(librosa.feature.mfcc(y=X, sr=samp_rate, n_mfcc=40), axis=1)

    emo_num = filename[6:8]
    arr_val = mfcc_val, emo_num

    dataset_arr.append(arr_val)

X, y = zip(*dataset_arr)
X = np.asarray(X)
y = np.asarray(y)
print(X.shape)
print(type(X))
print(y.shape)
print(type(y))

import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.67)

x_train_cnn = np.expand_dims(X_train, axis=2)
x_test_cnn = np.expand_dims(X_test, axis=2)

lb = LabelEncoder()

y_train = np_utils.to_categorical(lb.fit_transform(y_train))
y_test = np_utils.to_categorical(lb.fit_transform(y_test))
print(x_train_cnn.shape)
print(x_test_cnn.shape)
print(y_train.shape)
print(y_test.shape)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv1D, MaxPooling1D

model = Sequential()
model.add(Conv1D(256, 5, padding='same', input_shape=(x_train_cnn.shape[1],x_train_cnn.shape[2])))
model.add(Activation('relu'))
model.add(Conv1D(128, 5, padding='same'))
model.add(Activation('relu'))
model.add(Dropout(0.1))
model.add(MaxPooling1D(pool_size=8))
model.add(Conv1D(128, 5, padding='same'))
model.add(Activation('relu'))
model.add(Conv1D(128, 5, padding='same'))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(y_train.shape[1]))
model.add(Activation('softmax'))
opt = tf.keras.optimizers.RMSprop(lr=0.00001, decay=1e-6)

model.summary()

model.compile(loss='categorical_crossentropy', optimizer=opt,metrics=['accuracy'])
model_convnet = model.fit(x_train_cnn, y_train, batch_size=16, epochs=800, validation_data=(x_test_cnn, y_test))

plt.plot(model_convnet.history['loss'])
 plt.plot(model_convnet.history['val_loss'])
 plt.title('model loss')
 plt.xlabel('epochs')
 plt.ylabel('loss')
 plt.legend(['train','test'], loc='upper left')
 plt.show()

X_n = x_test_cnn
predictions = model.predict(X_n)
print(predictions[0])

model_name = "Speech_Emotion_Recognition800.h5"
save_dir = os.path.join(os.getcwd(),'saved_cnn')
if not os.path.isdir(save_dir):
  os.makedirs(save_dir)

model_path = os.path.join(save_dir, model_name)
model.save(model_path)
print(model_path)

